services:
  frontend:
    build: 
      context: ./frontend/
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Ignore local node_modules
    ports:
      - 3000:5173
    environment:
    - CHOKIDAR_USEPOLLING=true
    - WATCHPACK_POLLING=true
    - WDS_SOCKET_PORT=0
 
  post-creation-service:
    build: 
      context: ./post-creation-service/
      dockerfile: Dockerfile
    
    volumes:
      - ./post-creation-service:/app
      - /app/node_modules  # Ignore local node_modules
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - WDS_SOCKET_PORT=0


  comment-creation-service:
    build: 
      context: ./comment-creation-service/
      dockerfile: Dockerfile
    
    volumes:
      - ./comment-creation-service:/app
      - /app/node_modules  # Ignore local node_modules
    ports:
      - 3002:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - WDS_SOCKET_PORT=0
  query-service:
    build: 
      context: ./query-service/
      dockerfile: Dockerfile
    volumes:
      - ./query-service:/app
      - /app/node_modules  # Ignore local node_modules
    ports:
      - 3003:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - WDS_SOCKET_PORT=0
  event-bus:
    build: 
      context: ./event-bus/
      dockerfile: Dockerfile
    volumes:
      - ./event-bus:/app
      - /app/node_modules  # Ignore local node_modules
    ports:
      - 3005:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - WDS_SOCKET_PORT=0