services:
  frontend:
    build: 
      context: ./frontend/
      dockerfile: ../dockerfiles/Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Ignore local node_modules
    ports:
      - 3000:5173
    restart: always
 
 
  post-service:
    build: 
      context: ./post-service/
      dockerfile: ../dockerfiles/Dockerfile
    restart: always
    volumes:
      - ./post-service:/app
      - /app/node_modules  # Ignore local node_modules
    ports:
      - 3001:3000
 

  comment-service:
    build: 
      context: ./comment-service/
      dockerfile: ../dockerfiles/Dockerfile
    restart: always
    volumes:
      - ./comment-service:/app
      - /app/node_modules  # Ignore local node_modules
    ports:
      - 3002:3000
 
  query-service:
    build: 
      context: ./query-service/
      dockerfile: ../dockerfiles/Dockerfile
    restart: always
    volumes:
      - ./query-service:/app
      - /app/node_modules  # Ignore local node_modules
    ports:
      - 3003:3000
 
  event-bus:
    build: 
      context: ./event-bus/
      dockerfile: ../dockerfiles/Dockerfile
    restart: always
    volumes:
      - ./event-bus:/app
      - /app/node_modules  # Ignore local node_modules
    ports:
      - 3005:3000
 

  comment-moderation-service:
    build: 
      context: ./comment-moderation-service/
      dockerfile: ../dockerfiles/Dockerfile
    restart: always
    volumes:
      - ./comment-moderation-service:/app
      - /app/node_modules  # Ignore local node_modules
    ports:
      - 3006:3000
 